use_frameworks!

platform :ios, '9.0'

target 'YJDomainManager_Example' do
  pod 'YJDomainManager', :path => '../'

  target 'YJDomainManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
